modLoader="javafml"
loaderVersion="[41,)"
license="GNU AGPLv3"
issueTrackerURL="https://github.com/Nyphet/torch-hit/issues" #optional
[[mods]]
modId="torchhit"
version="${file.jarVersion}"
displayName="Torch hit!"
updateJSONURL="https://raw.githubusercontent.com/Nyphet/torch-hit/master/forge/updates.json" #optional
displayURL="https://github.com/Nyphet/torch-hit/tree/1.19/main" #optional
logoFile="torch-hit.gif" #optional
authors="Crystal Spider" #optional
description="Attack with torches to deal fire damage!"
[[dependencies.torchhit]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchhit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
#optional
