modLoader="javafml"
loaderVersion="[40,)"
license="GNU AGPLv3"
issueTrackerURL="https://github.com/Nyphet/torch-hit/issues" #optional
[[mods]]
modId="modid"
version="${modVersion}"
displayName="${modTitle}"
updateJSONURL="https://raw.githubusercontent.com/Nyphet/torch-hit/master/forge/updates.json" #optional
displayURL="https://github.com/Nyphet/torch-hit/tree/${mcVersion}" #optional
logoFile="torch-hit.gif" #optional
# credits="Thank who deserves it." #optional
authors="${author}" #optional
description="Attack with torches to deal fire damage!"
[[dependencies.modid]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeVersion},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modid]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion},)"
    ordering="NONE"
    side="BOTH"
#optional
