# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 21
mod_version = 7.1.1
group = it.crystalnest
mod_authors = Crystal Spider
mod_title = Torch hit!
mod_id = torch_hit
mod_id_kebab = torch-hit
license = GPL-3.0-or-later
description = Attack with torches!
credits =
github_user = crystal-nest
curseforge_id = 629434
minecraft_version = 1.21
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft = 1.21.1
parchment_version = 2024.11.17
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21-20240613.152323

# Fabric (https://fabricmc.net/develop/)
fabric_version = 0.102.0+1.21
fabric_loader_version = 0.16.1

# NeoForge (https://projects.neoforged.net/neoforged/neoforge)
neoforge_version = 21.0.167
neoforge_loader_version_range = [21.0,)

# Dependencies
cobweb_version = 1.4.0
fcap_version = 21.0.1
prometheus_version = 1.0.0
soul_fire_d_version = 6.0.0

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
